### ISSUE TITLE
Game crashing at world creation

### ISSUE THREAD

**Issue by aninusmuffin** [LunaPixelStudios/Versatile#1]
### Describe the Bug

Just installed the pack and i cant play it :(

Repurposed Structures seems to be the cause:

`Caused by: com.google.gson.JsonParseException: Error loading registry data: Unknown registry key in ResourceKey[minecraft:root / minecraft:worldgen/structure_type]: repurposed_structures:generic_jigsaw_structure`

### Reproduction Steps

1. Install the modpack form modrinth
2. Launch
3. Click on Singleplayer
4. Crash!
...

### Crash Report or Log

https://mclo.gs/pIeMXUs

### Operating System

Fedora Linux 38

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v1

### Optifine

No

**Comment by chorbintime** [comment]
Did you update or add mods?

**Comment by aninusmuffin** [comment]
No

**Comment by chorbintime** [comment]
update or remove the repurposed structures mod
