### ISSUE TITLE
Game crashing when creating a new world

### ISSUE THREAD

**Issue by ghost** [LunaPixelStudios/Versatile#10]
### Describe the Bug

When i create a new world by clicking on singleplayer, it gets stuck at "Preparing for world creation..." and after one or two minutes it crashes.

### Reproduction Steps

1. Installing Versatile on Modrinth
2. Clicking "Play"
3. Clicking on singleplayer
4. Crash

### Crash Report or Log

https://mclo.gs/nVRxTL3

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v7.5

### Optifine

No

**Comment by SHXRKIEgg** [comment]
Remove the mods you added

**Comment by kleiders3010** [comment]
Can confirm that this issue happens with a default instance with no modifications (Including no mods added or removed, no datapacks added or removed, and no settings or configuration changes) @SHXRKIEgg
