### ISSUE TITLE
game crash when I press single player

### ISSUE THREAD

**Issue by Luissav** [LunaPixelStudios/Versatile#11]
### Describe the Bug

Hi, Im trying to play this mod but when I try to select "Single Player" it doesn't give me de option to select a new world etc. It just starts to attempt to create a world directly and thats when the game freezes.
I tried to reinstall the modpack, reboot my pc and close the launcher, but I haven't made advancements.
Hope somebody can aid me with this bug so I can play this modpack.

### Reproduction Steps

1.Launch modpack
2.When in the menu select single player
3. Game skips world selection and starts creating a world
4. Game crash

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

7.5

### Optifine

No

### Other Mods

none

**Comment by chorbintime** [comment]
we cant help if you do not provide logs. please send the file named latest in your logs folder, or send the crash report in the crash reports folder
