### ISSUE TITLE
[7.5] Crash on creating certain structures

### ISSUE THREAD

**Issue by Seegras** [LunaPixelStudios/Versatile#12]
### Describe the Bug

`Caused by: com.mojang.brigadier.exceptions.CommandSyntaxException: Unknown block type 'minecraft:deepslate_stairs'
`
That there probably. Crash-report attached. 
I guess it depends where on where you spawn, and what structures it places near you. Maybe I could walk off in a different direction, and never have this structure generated and it wouldn't crash. 

[crash-2024-02-05_13.41.59-server.txt](https://github.com/LunaPixelStudios/Versatile/files/14165850/crash-2024-02-05_13.41.59-server.txt)

### Reproduction Steps

1.
2.
3.
...

### Operating System

Linux

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

7.5

### Optifine

No

**Comment by chorbintime** [comment]
will be fixed in the next update - you can update the datapacks & structure mods manually if you'd like - just make sure to copy the datapacks over to the paxi -> datapacks folder
