### ISSUE TITLE
Game crashes when pressing singleplayer

### ISSUE THREAD

**Issue by Q9r8** [LunaPixelStudios/Versatile#13]
### Describe the Bug

I have not modified the modpack at all. I installed and played the modpack off of the Modrinth app. I just open the game, press singleplayer, and it crashes.

### Reproduction Steps

1. Launch Modpack
2. Press singleplayer
3. Game says "preparing for world creation"
4. Crashes

### Crash Report or Log

https://pastebin.com/izYEWiTK

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

7.5

### Optifine

No

### Other Mods

None

**Comment by chorbintime** [comment]
Allocate 6-8 gigabytes of RAM
