### ISSUE TITLE
Mob Health and Visual bug

### ISSUE THREAD

**Issue by Sveap** [LunaPixelStudios/Versatile#14]
### Describe the Bug

So there is this annoying bug and i have not found any solution. 

Whenever i hit any mob for "its first hit". it has a chance to just insta regenerate to max health. And when i instakill the mob (its first hit) it has a chance to just insta regenerate to max health and causes that weird visual bug. The loot and exp still drops but it just keeps walking around the world red like that. by killing it in that form it dies completely, no extra drops. 

I can bypass this by hitting it (for its first time) without killing it, basically starting with a punch. Another hit would then not be insta regenerated meaning i could insta kill it after the first hit. Again, it's annoying when going with a high critical chance and damage build.

Using Minecrat 1.19.2 and versatile 7.5 with no extra mods. BisectHosting server.

https://github.com/LunaPixelStudios/Versatile/assets/168112089/5267dbd3-2b94-4c77-b286-2f8b8e4c9ea8

### Reproduction Steps

1. Hit or instakill any mob for "its first time". Doesn't happen all the time but very often. 

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

7.5

### Optifine

No

**Comment by chorbintime** [comment]
will be looked into for the next update - thank you for the report. in the meantime you could try updating the mods related to health / scaling
