### ISSUE TITLE
Fehlercode beim joinen von einem nitrado server

### ISSUE THREAD

**Issue by dusselphil17** [LunaPixelStudios/Versatile#15]
### Describe the Bug

Immer wenn ich auf meinen nitrado server joinen will kommt dieser fehlercode (Connection Lost
Internal Exception: io.netty.handler.codec.DecoderException: io.netty.handler.codec.EncoderException:
java.io.IOException: Root tag must be a named compound tag). ich weiß nicht wie ich den beheben kann

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![Screenshot 2024-05-29 174837](https://github.com/LunaPixelStudios/Versatile/assets/171182291/377a69ad-7f39-45db-9c52-34f031d11efd)

### Operating System

windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

V 7.5

### Optifine

No

**Comment by chorbintime** [comment]
Please ask the Nitrado support team
