### ISSUE TITLE
Crash when create new world

### ISSUE THREAD

**Issue by MbtMarco** [LunaPixelStudios/Versatile#2]
### Describe the Bug

Minecrash crash when i try to create new world

### Reproduction Steps

Play Minecraft :D

### Crash Report or Log

https://mclo.gs/D3y9w7V

### Operating System

MacOS

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

V2

### Optifine

No

**Comment by chorbintime** [comment]
Remove any java args you added. If the issue persists or you didnt add any args, switch to ATLauncher.
