### ISSUE TITLE
Incompatible Mods (Data Attributes and Illager Expansion Rematch)

### ISSUE THREAD

**Issue by NarwhalAndMe** [LunaPixelStudios/Versatile#3]
### Describe the Bug

When a Marauder spawns, game crashes. https://github.com/CleverNucleus/data-attributes/issues/93 and https://github.com/ZekeSmith/Illager-Expansion-Rematch/pull/11 address this. Illager Expansion Rematch hasn't been updated since 2022, so I don't expect it to be fixed soon.

### Reproduction Steps

1. Join World
2. Spawn Marauder
3. Crash

### Crash Report or Log

https://mclo.gs/Y0lDnJn

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v2

### Optifine

No

### Other Mods

Tom's Simple Storage Mod, Diggus Maximus, StackCalc Revived, Mine Treasure, Simply Swords, Knaves' Needs, and DarkLoot.

**Comment by SHXRKIEgg** [comment]
Remove Illager Expansion Rematch, also huge v3 update coming soon

**Comment by NarwhalAndMe** [comment]
i already did, excited for the new update!
