### ISSUE TITLE
Versatile v6 - Saving but not using keybinds.

### ISSUE THREAD

**Issue by GayKiwi** [LunaPixelStudios/Versatile#5]
### Describe the Bug

When changing basic keybinds (**Open Inventory**), it saves the config, but doesn't let that key be used.

### Reproduction Steps

Change **Open Inventory** to **Q**

It saves, can even exit the game, and it still shows as **Q**.

When you press **Q** it drops items (default behaviour).

If you rebind **Drop Item** to **Z**, **Q** will still drop item and **Z** does nothing (If you remove all the functions **Z** has).

### Operating System

Windows 10 64bit

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

6

### Optifine

I used Optifine

**Comment by SHXRKIIE** [comment]
Update to reuplaoded v6 version
