### ISSUE TITLE
Render distance is locked to 10 on singleplayer

### ISSUE THREAD

**Issue by ghost** [LunaPixelStudios/Versatile#6]
### Describe the Bug

whenever I try to change render distance it always reverts back to 10 it does this when I try to increase or decrease the render distance, simulation distance can be changed, only render distance reverts back to 10

### Reproduction Steps

1. start a new world
2. go into settings and change render distance then exit
3. go back into settings and the render distance will be at 10

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v7.5

### Optifine

No

**Comment by chorbintime** [comment]
delete the defaultoptions mod
