### ISSUE TITLE
PlayerEx levels randomly resetting

### ISSUE THREAD

**Issue by Fxsch** [LunaPixelStudios/Versatile#7]
### Describe the Bug

My PlayerEx levels keep on resetting. According to [this issue on the PlayerEx GitHub](https://github.com/CleverNucleus/playerex/issues/54) it happens on world load/save and is caused by AttributeFix. I haven't been able to test it myself because it doesn't happen all the time and I've only noticed it in the middle of playing.

### Operating System

Arch Linux 6.5.7

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

7.5

### Optifine

No

### Other Mods

- [Additional Enchanted Miner](https://www.curseforge.com/minecraft/mc-mods/additional-enchanted-miner)
- [Create Crafts & Additions](https://modrinth.com/mod/createaddition)
- [Diagonal Windows](https://modrinth.com/mod/diagonal-windows)
- [ShieldDisruptor](https://modrinth.com/mod/shielddisruptor)

**Comment by Fxsch** [comment]
Just noticed it also happens with Magic levels (Magic tab in the inventory). I don't know if that's also from PlayerEx or if that's a different mod.

**Comment by Fxsch** [comment]
Just remembered that the levels also reset when I  went into another dimension on accident. I think I right clicked some blue thing and all the dark areas in that dimension were pitch black. No idea what that dimension was.

**Comment by chorbintime** [comment]
not much we can do if its a mod interaction - i'd suggest reporting it to the individual mod devs
