### ISSUE TITLE
Exception occurred in netty pipeline

### ISSUE THREAD

**Issue by Doominuke** [LunaPixelStudios/Versatile#8]
### Describe the Bug

When I join my server installation of this modpack from my pc instance, I get the following error. I believe I removed VR combat and Vivecraft but that's about it. On server side I removed the visual mods such as Lithium and Iris.

### Reproduction Steps

1. Install a new instance of Versatile from Modrinth onto a server.
2. Boot up the fresh instance and your pc's instance.
3. Attempt to join.
...

### Crash Report or Log

https://pastebin.com/qvM8Sh4P

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v7.5

### Optifine

No

**Comment by chorbintime** [comment]
Lithium is not a visual mod. Do not remove it.

Please retry on an unmodified instance.

**Comment by Doominuke** [comment]
Here is the clean install on both server and client. Too big for pastebin, same error.
[latest.log](https://github.com/LunaPixelStudios/Versatile/files/13659436/latest.log)

**Comment by chorbintime** [comment]
How did you run the server, step by step?

**Comment by Doominuke** [comment]
Would a video work for you or a list? I use Sparked Host/ Apollo as my server provider

**Comment by chorbintime** [comment]
likely an issue with your server host - please contact them

**Comment by Doominuke** [comment]
Is the any other server provider you'd be confident to say I can host my server on? My server provider is insisting it's the mod pack and not their servers which is probably false.

**Comment by chorbintime** [comment]
you could give [bisect](https://www.bisecthosting.com/p/lunapixel) a shot

**Comment by Doominuke** [comment]
I did give them a shot and unfortunately they didn't work either about two days ago. But something changed and I guess somehow after another fresh install on my original server hosting site, something changed and it worked at the end of the day. So everything works now, dont know how, but that's fine by me.
