### ISSUE TITLE
Unable to change render distance

### ISSUE THREAD

**Issue by 1SOH** [LunaPixelStudios/Versatile#9]
### Describe the Bug

I am unable to change the render distance from 10. I will go into the video settings, change it to 32, exit. And when I go back into video settings, it's still on 10. There was a previous bug report for this same issue, the solution said to remove the "defaultoptions mod", but I cannot find such a mod on the list. 

### Reproduction Steps

1. Create New world
2. Open settings and change render distance
3. Exit and open settings again, the render distance is still 10.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Versatile v7.5

### Optifine

No

### Other Mods

N/A

**Comment by Axolotl48** [comment]
the mod might be "your options shall be respected"
I'm having the same problem, but I haven't looked into it yet

**Comment by 1SOH** [comment]
I removed the "your options shall be respected" mod and unfortunately that didn't change anything. Thanks for the help though!

**Comment by SHXRKIEgg** [comment]
Update Iris and Sodium
